add_definitions(-DMSGPACK_NO_BOOST)
set(MSGPACK_ENDIAN_LITTLE_BYTE 1 CACHE INTERNAL "")
set(MSGPACK_USE_BOOST OFF CACHE BOOL "" FORCE)
set(MSGPACK_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(MSGPACK_BUILD_TESTS OFF CACHE BOOL "" FORCE)
add_subdirectory("lib/msgpack-c")
include_directories("lib/msgpack-c/include")