name: Github Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dotnet-build-no-warnings:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore src/SharpDetect.sln
    - name: Build & Treat Warnings as Errors
      run: dotnet build src/SharpDetect.sln --no-restore --no-incremental /warnaserror
      
  native-build-windows:
    runs-on: windows-2022
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Publish native AOT
      run: |
        cd src/SharpDetect.ManagedProfiler/SharpDetect.ManagedProfiler/Scripts
        ./publish-win-x64-aot-release.cmd

  dotnet-unit-tests:
    runs-on: ubuntu-latest
    needs: dotnet-build-no-warnings
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore src/Tests/SharpDetect.UnitTests/SharpDetect.UnitTests.csproj
    - name: Build & Ignore Warnings
      run: dotnet build src/Tests/SharpDetect.UnitTests/SharpDetect.UnitTests.csproj --no-restore --no-incremental /property:WarningLevel=0
    - name: Test
      run: dotnet test src/Tests/SharpDetect.UnitTests/SharpDetect.UnitTests.csproj --no-build --verbosity normal --logger GitHubActions