name: CI

on: ["push"]

jobs:
  build-dotnet-no-warnings:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Restore dependencies
      run: dotnet restore src/SharpDetect.sln
    - name: Build & Treat Warnings as Errors
      run: dotnet build src/SharpDetect.sln --no-restore --no-incremental /warnaserror
      
  build-native-windows-x64:
    runs-on: windows-2022
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Publish native AOT
      run: |
        cd src/SharpDetect.Profiler/Scripts
        ./publish-win-x64-aot-debug.ps1

  build-native-linux-x64:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Publish native AOT
      run: |
        cd src/SharpDetect.Profiler/Scripts
        sh ./publish-linux-x64-aot-debug.sh
    
  unit-tests-dotnet:
    runs-on: ubuntu-latest
    needs: build-dotnet-no-warnings
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Restore dependencies
      run: dotnet restore src/Tests/SharpDetect.UnitTests/SharpDetect.UnitTests.csproj
    - name: Build (dotnet)
      run: dotnet build src/Tests/SharpDetect.UnitTests/SharpDetect.UnitTests.csproj --no-restore --no-incremental /property:WarningLevel=0
    - name: Test
      run: dotnet test src/Tests/SharpDetect.UnitTests/SharpDetect.UnitTests.csproj --no-build --verbosity normal --logger GitHubActions

  ilverify-rewriting-verification:
    runs-on: ubuntu-22.04
    needs: [build-dotnet-no-warnings, build-native-linux-x64, unit-tests-dotnet]
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Install ILVerify
      run: dotnet tool install --global dotnet-ilverify
    - name: Restore dependencies
      run: dotnet restore src/Tests/SharpDetect.ILVerifications/SharpDetect.ILVerifications.csproj
    - name: Build (dotnet)
      run: dotnet build src/Tests/SharpDetect.ILVerifications/SharpDetect.ILVerifications.csproj --no-restore --no-incremental /property:WarningLevel=0
    - name: Publish (native)
      run: |
        cd src/SharpDetect.Profiler/Scripts
        sh ./publish-linux-x64-aot-debug.sh
    - name: ILVerify Tests
      run: dotnet test src/Tests/SharpDetect.ILVerifications/SharpDetect.ILVerifications.csproj --no-build --verbosity normal --logger GitHubActions

  e2e-tests-windows-x64:
    runs-on: windows-2022
    needs: [build-dotnet-no-warnings, build-native-windows-x64, unit-tests-dotnet]
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Install ILVerify
      run: dotnet tool install --global dotnet-ilverify
    - name: Restore dependencies
      run: dotnet restore src/Tests/SharpDetect.E2ETests/SharpDetect.E2ETests.csproj
    - name: Build (dotnet)
      run: dotnet build src/Tests/SharpDetect.E2ETests/SharpDetect.E2ETests.csproj --no-restore --no-incremental /property:WarningLevel=0
    - name: Publish (native)
      run: |
        cd src/SharpDetect.Profiler/Scripts
        ./publish-win-x64-aot-debug.ps1
    - name: E2E Tests
      run: dotnet test src/Tests/SharpDetect.E2ETests/SharpDetect.E2ETests.csproj --no-build --verbosity normal --logger GitHubActions

  e2e-tests-linux-x64:
    runs-on: ubuntu-22.04
    needs: [build-dotnet-no-warnings, build-native-linux-x64, unit-tests-dotnet]
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Restore dependencies
      run: dotnet restore src/Tests/SharpDetect.E2ETests/SharpDetect.E2ETests.csproj
    - name: Build (dotnet)
      run: dotnet build src/Tests/SharpDetect.E2ETests/SharpDetect.E2ETests.csproj --no-restore --no-incremental /property:WarningLevel=0
    - name: Publish (native)
      run: |
        cd src/SharpDetect.Profiler/Scripts
        sh ./publish-linux-x64-aot-debug.sh
    - name: E2E Tests
      run: dotnet test src/Tests/SharpDetect.E2ETests/SharpDetect.E2ETests.csproj --no-build --verbosity normal --logger GitHubActions