name: CI

on: ["push"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        rid: [win-x64, linux-x64]
        exclude:
          # Cross-compilation is not supported 
          - os: ubuntu-latest
            rid: win-x64
          - os: windows-latest
            rid: linux-x64
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.*
    - name: Build
      run: |
        cd src
        dotnet tool restore
        dotnet cake --rid=${{ matrix.rid }}

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        rid: [win-x64, linux-x64]
        exclude:
          # Cross-compilation is not supported 
          - os: ubuntu-latest
            rid: win-x64
          - os: windows-latest
            rid: linux-x64
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.*
    - name: Tests
      run: |
        cd src
        dotnet tool restore
        dotnet cake --rid=${{ matrix.rid }} --target=Tests