name: Github Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/SharpDetect.sln
    - name: Build & Ignore Warnings
      run: dotnet build src/SharpDetect.sln --no-restore --no-incremental /property:WarningLevel=0

  build-no-warnings:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/SharpDetect.sln
    - name: Build & Treat Warnings as Errors
      run: dotnet build src/SharpDetect.sln --no-restore --no-incremental /warnaserror

  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/SharpDetect.sln
    - name: Build & Ignore Warnings
      run: dotnet build src/SharpDetect.sln --no-restore --no-incremental /property:WarningLevel=0
    - name: Test
      run: dotnet test src/SharpDetect.sln --no-build --verbosity normal