name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dotnet-build-no-warnings:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Restore dependencies
      run: dotnet restore src/SharpDetect.sln
    - name: Build & Treat Warnings as Errors
      run: dotnet build src/SharpDetect.sln --no-restore --no-incremental /warnaserror
      
  native-build-windows:
    runs-on: windows-2022
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Publish native AOT
      run: |
        cd src/SharpDetect.Profiler/Scripts
        ./publish-win-x64-aot-debug.ps1

  dotnet-unit-tests:
    runs-on: ubuntu-latest
    needs: dotnet-build-no-warnings
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Restore dependencies
      run: dotnet restore src/Tests/SharpDetect.UnitTests/SharpDetect.UnitTests.csproj
    - name: Build (dotnet)
      run: dotnet build src/Tests/SharpDetect.UnitTests/SharpDetect.UnitTests.csproj --no-restore --no-incremental /property:WarningLevel=0
    - name: Test
      run: dotnet test src/Tests/SharpDetect.UnitTests/SharpDetect.UnitTests.csproj --no-build --verbosity normal --logger GitHubActions

  windows-e2e-tests:
    runs-on: windows-2022
    needs: [dotnet-build-no-warnings, native-build-windows, dotnet-unit-tests]
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Restore dependencies
      run: dotnet restore src/Tests/SharpDetect.E2ETests/SharpDetect.E2ETests.csproj
    - name: Build (dotnet)
      run: dotnet build src/Tests/SharpDetect.E2ETests/SharpDetect.E2ETests.csproj --no-restore --no-incremental /property:WarningLevel=0
    - name: Publish (native)
      run: |
        cd src/SharpDetect.Profiler/Scripts
        ./publish-win-x64-aot-debug.ps1
    - name: Test
      run: dotnet test src/Tests/SharpDetect.E2ETests/SharpDetect.E2ETests.csproj --no-build --verbosity normal --logger GitHubActions