name: Publish
on:
  workflow_dispatch:
  
jobs:
  build-dotnet:
    runs-on: windows-2022
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Restore dependencies
      run: dotnet restore src/SharpDetect.sln
    - name: Publish (dotnet)
      run: |
        dotnet publish -c Release src/SharpDetect.Console
        dotnet publish -c Release src/SharpDetect.Plugins
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sharpdetect
        path: |
          src/SharpDetect.Console/bin/Release/net7.0/publish
          src/SharpDetect.Plugins/bin/Release/net7.0/publish
        
  build-native-windows-x64:
    runs-on: windows-2022
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Publish (native)
      run: |
        cd src/SharpDetect.Profiler/Scripts
        ./publish-win-x64-aot-release.ps1
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: profiler-windows-x64
        path: |
          src/SharpDetect.Profiler/bin/Release/net7.0/win-x64/native/SharpDetect.Profiler.dll

  build-native-linux-x64:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Publish (native)
      run: |
        cd src/SharpDetect.Profiler/Scripts
        sh ./publish-linux-x64-aot-release.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: profiler-linux-x64
        path: |
          src/SharpDetect.Profiler/bin/Release/net7.0/linux-x64/native/SharpDetect.Profiler.so